# Utiliza a imagem oficial do Kali Linux (versão leve/rolling)
FROM kalilinux/kali-rolling:latest

# Define o modo não interativo para evitar prompts durante a instalação
ENV DEBIAN_FRONTEND=noninteractive

# Atualiza e instala ferramentas de rede, Python e serviços
# Nota: Adicionei o comando 'kali-archive-keyring' para garantir a validade dos repositórios
RUN apt-get update && apt-get install -y \
    kali-archive-keyring \
    python3 python3-pip \
    iproute2 iputils-ping tcpdump \
    nginx mariadb-server telnetd xinetd ngrep \
    masscan nmap hping3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
